NODE_BIN=./node_modules/.bin

.PHONY: help
help:  ## This.
	@perl -ne 'print if /^[a-zA-Z_.-]+:.*## .*$$/' $(MAKEFILE_LIST) \
	| sort \
	| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

DOCKER_IMAGE_NAME=xqueue-watcher
DOCKER_CONFIG_DIR=$(PWD)/conf.d

.PHONY: docker.build
docker.build: ## Build the latest container image
	docker build -t $(DOCKER_IMAGE_NAME):latest .

.PHONY: docker.run
docker.run:  ## Run the local container image
	docker run -v $(DOCKER_CONFIG_DIR):/edx/etc/xqueue_watcher \
		$(DOCKER_IMAGE_NAME):latest \
	;

.PHONY: docker.shell
docker.shell:  ## Start a container in a bash shell
	docker run -v $(DOCKER_CONFIG_DIR):/edx/etc/xqueue_watcher \
		--rm -it --name $(DOCKER_IMAGE_NAME) \
		$(DOCKER_IMAGE_NAME):latest \
		bash

upgrade: export CUSTOM_COMPILE_COMMAND=make upgrade
upgrade: ## Update the requirements/*.txt files with the latest packages satisfying requirements/*.in
	pip install -q -r requirements/pip_tools.txt
	pip-compile --upgrade -o requirements/pip_tools.txt requirements/pip_tools.in
	pip-compile --upgrade -o requirements/base.txt requirements/base.in
	pip-compile --upgrade -o requirements/production.txt requirements/production.in
	pip-compile --upgrade -o requirements/test.txt requirements/test.in
	pip-compile --upgrade -o requirements/travis.txt requirements/travis.in

requirements:
	pip install -qr requirements/production.txt --exists-action w

test.requirements:
	pip install -q -r requirements/travis.txt --exists-action w

test: test.requirements  ## Run the test suite
	tox

clean:  ## Delete generated byte code and coverage reports
	find . -name '*.pyc' -delete

# Targets in a Makefile which do not produce an output file with the same name as the target name
.PHONY: help requirements clean
