help:
	@echo ''
	@echo 'Makefile for the xqueue-watcher'
	@echo ''
	@echo 'Usage:'
	@echo '    make requirements        sync dev dependencies with uv'
	@echo '    make test                run python unit-tests'
	@echo '    make docker-build        build the grader base Docker image'
	@echo '    make local-run           run locally with docker-compose'
	@echo '    make clean               delete generated byte code'
	@echo ''

requirements:
	uv sync

test: requirements
	uv run pytest --cov=xqueue_watcher --cov-report=xml tests

docker-build:
	docker build -t xqueue-watcher:local .
	docker build -t grader-base:local -f grader_support/Dockerfile.base .

local-run:
	docker compose up

clean:
	find . -name '*.pyc' -delete

.PHONY: help requirements test docker-build local-run clean
