
MANAGER_CONFIG_DEFAULTS = {
    'HTTP_BASIC_AUTH': None,
    'POLL_TIME': 10,
    'REQUESTS_TIMEOUT': 1,
    'POLL_INTERVAL': 1,
    'IDLE_POLL_INTERVAL': 60,
    'LOGIN_POLL_INTERVAL': 5,
    'FOLLOW_CLIENT_REDIRECTS': False
}
